# Generated by Django 4.2.6 on 2023-11-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_address_city_alter_address_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='interest_in',
            field=models.CharField(blank=True, choices=[('donation', 'Donation'), ('volunteering', 'Volunteering')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='in_workshops',
            field=models.ManyToManyField(blank=True, related_name='interest_workshops', to='accounts.workshop'),
        ),
    ]
