# Generated by Django 4.2.6 on 2023-10-29 13:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('asrams', '0002_remove_asram_acharya_asram_asram_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asram',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asram',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='asram',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asram',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
