# Generated by Django 4.2.6 on 2023-11-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrams', '0003_alter_asram_city_alter_asram_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asram',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
