# Generated by Django 4.2.6 on 2023-10-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wanted', models.TextField(max_length=300)),
                ('wanted_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
