# Generated by Django 4.2.6 on 2023-11-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_featurerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wated_title', models.CharField(max_length=50)),
                ('wanted', models.TextField(max_length=300)),
                ('wanted_name', models.CharField(max_length=30)),
                ('wanted_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
