# Generated by Django 4.2.6 on 2023-11-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='wanted_by',
            field=models.EmailField(max_length=254),
        ),
    ]
