# Generated by Django 4.2.6 on 2023-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='main_image',
            field=models.ImageField(default='', upload_to='book/main/'),
            preserve_default=False,
        ),
    ]
