# Generated by Django 4.2.6 on 2023-10-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookorder',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='bookorderitem',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
