# Generated by Django 4.2.6 on 2023-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_bookorderitem_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='gateway_reference',
            field=models.TextField(),
        ),
    ]
