# Generated by Django 4.2.6 on 2023-10-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_ordertransaction_gateway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertransaction',
            old_name='gateway_reference',
            new_name='trxID',
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirm', 'confirm'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=100),
        ),
    ]
