# Generated by Django 4.2.6 on 2023-11-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_ordertransaction_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
