# Generated by Django 4.2.6 on 2023-11-01 16:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_ordertransaction_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avialable_country',
            field=django_countries.fields.CountryField(default='BD', max_length=747, multiple=True),
        ),
    ]
