# Generated by Django 4.2.6 on 2023-11-01 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_avialable_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='screenshoot',
            field=models.FileField(default='', upload_to='transactions/screenshoot', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf'], message='Only image (jpg, jpeg, png, gif) and PDF files are allowed.')]),
            preserve_default=False,
        ),
    ]
