# Generated by Django 4.2.6 on 2023-11-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_ordertransaction_screenshoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='invoice', serialize=False, to='book.bookorder')),
                ('filepath', models.FileField(upload_to='payment_instruction')),
                ('validity', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
