# Generated by Django 4.2.6 on 2023-11-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_orderinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderinvoice',
            name='filepath',
            field=models.FileField(upload_to='payment_instruction/'),
        ),
    ]
