# Generated by Django 4.2.6 on 2023-11-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_orderinvoice_paid_orderinvoice_paid_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invoice_initiatd', 'Invoice Initiatd'), ('processing', 'Processing'), ('confirm', 'Confirm'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=100),
        ),
    ]
