# Generated by Django 4.2.6 on 2023-11-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_bookorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoice',
            name='gateway',
            field=models.CharField(default='', max_length=50),
        ),
    ]
