# Generated by Django 4.2.6 on 2023-11-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_orderinvoice_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='check_and_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
