# Generated by Django 4.2.6 on 2023-11-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_alter_bookorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_order_items', to='book.bookorder'),
        ),
    ]
